Added Instabase, fixed TD format issue
uwcsc/winter2022-internships pull request #13
Opened 2021-09-02 03:09 UTC by taziksh

2021-09-02 07:34 UTC, kallentu requested changes

2021-09-02 07:34 UTC, kallentu commented on README.md
> +| [Instabase](https://instabase.com/careers/#positions) | SWE | San Francisco, Menlo Park, & New York City | | |
Feel free to move this to the bottom-most line. We are going to start making this list chronologically added.

2021-09-02 19:20 UTC, taziksh reviewed
Sure, that works

2021-09-09 20:00 UTC, kallentu approved these changes

2021-09-09 20:00 UTC, merged